// export { AdminModule } from './admin.module';
export { NewServiceComponent } from './new-service/new-service.component';
export { UpdateServiceComponent } from './update-service/update-service.component';
export { DashboardComponent } from './dashboard/dashboard.component';
export { ListServicesComponent } from './list-services/list-services.component';
export { ApplicantComponent } from './applicant/applicant.component';
export { AdminComponent } from './admin/admin.component';
export { ApplicationComponent } from './application/application.component';
export { UsersComponent } from './users/users.component';
export { HorizontalNavigation } from './navigations/horizontal-navigation';
export { VarticalNavigation } from './navigations/vertical-navigation';